# Claude WM CLI Configuration File
verbose: true

# Application settings
app:
  name: "claude-wm-cli"
  version: "dev"
  
# Window management settings
window:
  default_timeout: 30
  max_retries: 2

# Claude AI integration settings
claude:
  model: "claude-3-sonnet"
  max_tokens: 4000
  temperature: 0.1