run:
  timeout: 5m
  go: "1.19"

linters:
  enable:
    - errcheck
    - gosimple
    - govet
    - ineffassign
    - staticcheck
    - typecheck
    - unused
    - gci
    - gofmt
    - goimports
    - gosec
    - misspell
    - revive
    - unconvert
    - unparam
    - whitespace

linters-settings:
  gci:
    sections:
      - standard
      - default
      - prefix(claude-wm-cli)
    skip-generated: true
  gosec:
    excludes:
      - G104 # Errors unhandled (we handle errors explicitly)
  revive:
    rules:
      - name: exported
        disabled: true
      - name: package-comments
        disabled: true

issues:
  exclude-rules:
    - path: _test\.go
      linters:
        - gosec
        - errcheck
  max-issues-per-linter: 0
  max-same-issues: 0

output:
  format: colored-line-number
  print-issued-lines: true
  print-linter-name: true